#include "CPUDefs.h"
namespace gb {



    CPU_INFO::Instruction CPU_INFO::unprefixed[0x100] = {
          { "NOP", INST_nop, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_rr_nn, 3, 12, { { REF_BC, false, true}, { REF_n16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$BC$_A, 1, 8, { { REF_$BC, false, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_rr, 1, 8, { { REF_BC, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_r, 1, 4, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_r, 1, 4, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_r_n, 2, 8, { { REF_B, false, true}, { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RLCA", INST_rlca, 1, 4, { },true, { FLAG_SET_0, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
          { "LD", INST_ld_$nn$_SP, 3, 20, { { REF_$a16, false, false}, { REF_SP, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADD", INST_add_HL_rr, 1, 8, { { REF_HL, false, true}, { REF_BC, false, true}},true, { FLAG_NULL, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "LD", INST_ld_A_$BC$, 1, 8, { { REF_A, false, true}, { REF_$BC, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "DEC", INST_dec_rr, 1, 8, { { REF_BC, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_r, 1, 4, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_r, 1, 4, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_r_n, 2, 8, { { REF_C, false, true}, { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RRCA", INST_rrca, 1, 4, { },true, { FLAG_SET_0, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
          { "STOP", INST_stop, 2, 4, { { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_rr_nn, 3, 12, { { REF_DE, false, true}, { REF_n16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$DE$_A, 1, 8, { { REF_$DE, false, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_rr, 1, 8, { { REF_DE, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_r, 1, 4, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_r, 1, 4, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_r_n, 2, 8, { { REF_D, false, true}, { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RLA", INST_rla, 1, 4, { },true, { FLAG_SET_0, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
          { "JR", INST_jr_PC_dd, 2, 12, { { REF_e8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADD", INST_add_HL_rr, 1, 8, { { REF_HL, false, true}, { REF_DE, false, true}},true, { FLAG_NULL, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "LD", INST_ld_A_$DE$, 1, 8, { { REF_A, false, true}, { REF_$DE, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "DEC", INST_dec_rr, 1, 8, { { REF_DE, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_r, 1, 4, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_r, 1, 4, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_r_n, 2, 8, { { REF_E, false, true}, { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RRA", INST_rra, 1, 4, { },true, { FLAG_SET_0, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
          { "JR", INST_jr_f_PC_dd, 2, 12, { { REF_NZ, false, true}, { REF_e8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_rr_nn, 3, 12, { { REF_HL, false, true}, { REF_n16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ldi_$HL$_A, 1, 8, { { REF_$HL, true, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_rr, 1, 8, { { REF_HL, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_r, 1, 4, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_r, 1, 4, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_r_n, 2, 8, { { REF_H, false, true}, { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "DAA", INST_daa, 1, 4, { },true, { FLAG_CONDITION, FLAG_NULL, FLAG_SET_0, FLAG_CONDITION} },
          { "JR", INST_jr_f_PC_dd, 2, 12, { { REF_Z, false, true}, { REF_e8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADD", INST_add_HL_rr, 1, 8, { { REF_HL, false, true}, { REF_HL, false, true}},true, { FLAG_NULL, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "LD", INST_ldi_A_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, true, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "DEC", INST_dec_rr, 1, 8, { { REF_HL, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_r, 1, 4, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_r, 1, 4, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_r_n, 2, 8, { { REF_L, false, true}, { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CPL", INST_cpl, 1, 4, { },true, { FLAG_NULL, FLAG_SET_1, FLAG_SET_1, FLAG_NULL} },
          { "JR", INST_jr_f_PC_dd, 2, 12, { { REF_NC, false, true}, { REF_e8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_rr_nn , 3, 12, { { REF_SP, false, true}, { REF_n16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ldd_$HL$_A, 1, 8, { { REF_$HL, false, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_rr, 1, 8, { { REF_SP, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_$HL$, 1, 12, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_$HL$, 1, 12, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_$HL$_n, 2, 12, { { REF_$HL, false, false}, { REF_n8, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "SCF", INST_scf, 1, 4, { },true, { FLAG_NULL, FLAG_SET_0, FLAG_SET_0, FLAG_SET_1} },
          { "JR", INST_jr_f_PC_dd, 2, 12, { { REF_C, false, true}, { REF_e8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADD", INST_add_HL_rr, 1, 8, { { REF_HL, false, true}, { REF_SP, false, true}},true, { FLAG_NULL, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "LD", INST_ldd_A_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "DEC", INST_dec_rr, 1, 8, { { REF_SP, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "INC", INST_inc_r, 1, 4, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_NULL} },
          { "DEC", INST_dec_r, 1, 4, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "LD", INST_ld_r_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CCF", INST_ccf, 1, 4, { },true, { FLAG_NULL, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_B, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_B, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_B, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_B, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_B, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_B, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_$HL$ , 1, 8, { { REF_B, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r , 1, 4, { { REF_B, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_C, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_C, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_C, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_C, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_C, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_C, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_$HL$ , 1, 8, { { REF_C, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_C, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_D, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_D, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_D, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_D, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_D, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_D, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_$HL$, 1, 8, { { REF_D, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_D, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_E, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_E, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_E, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_E, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_E, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_E, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_$HL$, 1, 8, { { REF_E, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_E, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_H, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_H, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_H, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_H, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_H, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_H, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_$HL$, 1, 8, { { REF_H, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_H, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_L, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_L, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_L, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_L, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_L, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_L, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_$HL$, 1, 8, { { REF_L, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_L, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$HL$_r, 1, 8, { { REF_$HL, false, false}, { REF_B, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$HL$_r, 1, 8, { { REF_$HL, false, false}, { REF_C, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$HL$_r, 1, 8, { { REF_$HL, false, false}, { REF_D, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$HL$_r, 1, 8, { { REF_$HL, false, false}, { REF_E, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$HL$_r, 1, 8, { { REF_$HL, false, false}, { REF_H, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$HL$_r, 1, 8, { { REF_$HL, false, false}, { REF_L, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "HALT", INST_halt, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$HL$_r, 1, 8, { { REF_$HL, false, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_r_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADD", INST_add_A_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADD", INST_add_A_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADD", INST_add_A_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADD", INST_add_A_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADD", INST_add_A_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADD", INST_add_A_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADD", INST_add_A_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADD", INST_add_A_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "ADC", INST_adc_A_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SUB", INST_sub_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_SET_1, FLAG_SET_1, FLAG_SET_0, FLAG_SET_0} },
          { "SBC", INST_sbc_A_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SBC", INST_sbc_A_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SBC", INST_sbc_A_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SBC", INST_sbc_A_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SBC", INST_sbc_A_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SBC", INST_sbc_A_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SBC", INST_sbc_A_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "SBC", INST_sbc_A_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_NULL} },
          { "AND", INST_and_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "AND", INST_and_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "AND", INST_and_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "AND", INST_and_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "AND", INST_and_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "AND", INST_and_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "AND", INST_and_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "AND", INST_and_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "XOR", INST_xor_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "XOR", INST_xor_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "XOR", INST_xor_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "XOR", INST_xor_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "XOR", INST_xor_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "XOR", INST_xor_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "XOR", INST_xor_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "XOR", INST_xor_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_SET_1, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "OR", INST_or_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "CP", INST_cp_r, 1, 4, { { REF_A, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "CP", INST_cp_r, 1, 4, { { REF_A, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "CP", INST_cp_r, 1, 4, { { REF_A, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "CP", INST_cp_r, 1, 4, { { REF_A, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "CP", INST_cp_r, 1, 4, { { REF_A, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "CP", INST_cp_r, 1, 4, { { REF_A, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "CP", INST_cp_$HL$, 1, 8, { { REF_A, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "CP", INST_cp_r, 1, 4, { { REF_A, false, true}, { REF_A, false, true}},true, { FLAG_SET_1, FLAG_SET_1, FLAG_SET_0, FLAG_SET_0} },
          { "RET", INST_ret_f, 1, 20, { { REF_NZ, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "POP", INST_pop_rr, 1, 12, {{REF_BC, false, true}},true, {FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL}},
          { "JP", INST_jp_f_nn, 3, 16, { { REF_NZ, false, true}, { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "JP", INST_jp_nn, 3, 16, { { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CALL", INST_call_f_nn, 3, 24, { { REF_NZ, false, true}, { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "PUSH", INST_push_rr, 1, 16, { { REF_BC, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADD", INST_add_A_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "RST", INST_rst_n, 1, 16, { { REF_$00, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RET", INST_ret_f, 1, 20, { { REF_Z, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RET", INST_ret, 1, 16, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "JP", INST_jp_f_nn, 3, 16, { { REF_Z, false, true}, { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "PREFIX", INST_PREFIX, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CALL", INST_call_f_nn, 3, 24, { { REF_Z, false, true}, { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CALL", INST_call_nn, 3, 24, { { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADC", INST_adc_A_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "RST", INST_rst_n, 1, 16, { { REF_$08, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RET", INST_ret_f, 1, 20, { { REF_NC, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "POP", INST_pop_rr, 1, 12, { { REF_DE, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "JP", INST_jp_f_nn, 3, 16, {{REF_NC, false, true}, {REF_a16, false, true}},true, {FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL}},
          { "ILLEGAL_D3", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CALL", INST_call_f_nn, 3, 24, { { REF_NC, false, true}, { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "PUSH", INST_push_rr, 1, 16, { { REF_DE, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "SUB", INST_sub_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "RST", INST_rst_n, 1, 16, { { REF_$10, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RET", INST_ret_f, 1, 20, { { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "RETI", INST_reti, 1, 16, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "JP", INST_jp_f_nn, 3, 16, { { REF_C, false, true}, { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_DB", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CALL", INST_call_f_nn, 3, 24, { { REF_C, false, true}, { REF_a16, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_DD", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "SBC", INST_sbc_A_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "RST", INST_rst_n, 1, 16, { { REF_$18, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LDH", INST_ld_$FF00_n$_A, 2, 12, { { REF_$a8, false, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "POP", INST_pop_rr, 1, 12, { { REF_HL, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$FF00_C$_A, 1, 8, { { REF_$C, false, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_E3", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_E4", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "PUSH", INST_push_rr, 1, 16, { { REF_HL, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "AND", INST_and_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_SET_0} },
          { "RST", INST_rst_n, 1, 16, { { REF_$20, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ADD", INST_add_SP_dd, 2, 16, { { REF_SP, false, true}, { REF_e8, false, true}},true, { FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "JP", INST_jp_HL, 1, 4, { { REF_HL, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_$nn$_A, 3, 16, { { REF_$a16, false, false}, { REF_A, false, true}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_EB", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_EC", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_ED", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "XOR", INST_xor_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "RST", INST_rst_n, 1, 16, { { REF_$28, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LDH", INST_ld_A_$FF00_n$, 2, 12, { { REF_A, false, true}, { REF_$a8, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "POP", INST_pop_rr, 1, 12, { { REF_AF, false, true}},true, { FLAG_CONDITION, FLAG_CONDITION, FLAG_CONDITION, FLAG_CONDITION} },
          { "LD", INST_ld_A_$FF00_C$, 1, 8, { { REF_A, false, true}, { REF_$C, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "DI", INST_di, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_F4", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "PUSH", INST_push_rr, 1, 16, { { REF_AF, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "OR", INST_or_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
          { "RST", INST_rst_n, 1, 16, { { REF_$30, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_HL_SP_dd, 2, 12, { { REF_HL, false, true}, { REF_SP, true, true}, { REF_e8, false, true}},true, { FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION, FLAG_CONDITION} },
          { "LD", INST_ld_SP_HL, 1, 8, { { REF_SP, false, true}, { REF_HL, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "LD", INST_ld_A_$nn$, 3, 16, { { REF_A, false, true}, { REF_$a16, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "EI", INST_ei, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_FC", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "ILLEGAL_FD", INST_ILLEGAL, 1, 4, { },true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
          { "CP", INST_cp_n, 2, 8, { { REF_A, false, true}, { REF_n8, false, true}},true, { FLAG_CONDITION, FLAG_SET_1, FLAG_CONDITION, FLAG_CONDITION} },
          { "RST", INST_rst_n, 1, 16, { { REF_$38, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
    };
    CPU_INFO::Instruction CPU_INFO::cbprefixed[0x100] = {
        { "RLC", INST_rlc_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RLC", INST_rlc_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RLC", INST_rlc_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RLC", INST_rlc_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RLC", INST_rlc_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RLC", INST_rlc_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RLC", INST_rlc_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RLC", INST_rlc_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RRC", INST_rrc_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RL", INST_rl_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "RR", INST_rr_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SLA", INST_sla_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRA", INST_sra_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SWAP", INST_swap_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SWAP", INST_swap_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SWAP", INST_swap_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SWAP", INST_swap_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SWAP", INST_swap_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SWAP", INST_swap_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SWAP", INST_swap_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SWAP", INST_swap_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_SET_0} },
        { "SRL", INST_srl_r, 2, 8, { { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRL", INST_srl_r, 2, 8, { { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRL", INST_srl_r, 2, 8, { { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRL", INST_srl_r, 2, 8, { { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRL", INST_srl_r, 2, 8, { { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRL", INST_srl_r, 2, 8, { { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRL", INST_srl_$HL$, 2, 16, { { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "SRL", INST_srl_r, 2, 8, { { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_0, FLAG_CONDITION} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_0, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_0, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_0, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_0, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_0, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_0, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_0, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_0, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_1, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_1, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_1, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_1, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_1, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_1, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_1, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_1, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_2, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_2, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_2, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_2, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_2, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_2, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_2, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_2, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_3, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_3, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_3, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_3, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_3, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_3, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_3, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_3, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_4, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_4, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_4, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_4, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_4, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_4, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_4, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_4, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_5, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_5, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_5, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_5, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_5, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_5, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_5, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_5, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_6, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_6, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_6, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_6, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_6, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_6, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_6, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_6, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_7, false, true}, { REF_B, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_7, false, true}, { REF_C, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_7, false, true}, { REF_D, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_7, false, true}, { REF_E, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_7, false, true}, { REF_H, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_7, false, true}, { REF_L, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_$HL$, 2, 12, { { REF_7, false, true}, { REF_$HL, false, false}},false, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "BIT", INST_bit_n_r, 2, 8, { { REF_7, false, true}, { REF_A, false, true}},true, { FLAG_CONDITION, FLAG_SET_0, FLAG_SET_1, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_0, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_0, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_0, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_0, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_0, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_0, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_$HL$, 2, 16, { { REF_0, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_0, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_1, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_1, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_1, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_1, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_1, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_1, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 16, { { REF_1, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_1, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_2, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_2, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_2, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_2, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_2, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_2, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_$HL$, 2, 16, { { REF_2, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_2, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_3, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_3, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_3, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_3, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_3, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_3, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_$HL$, 2, 16, { { REF_3, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_3, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_4, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_4, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_4, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_4, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_4, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_4, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_$HL$, 2, 16, { { REF_4, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_4, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_5, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_5, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_5, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_5, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_5, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_5, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_$HL$, 2, 16, { { REF_5, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_5, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_6, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_6, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_6, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_6, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_6, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_6, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_$HL$, 2, 16, { { REF_6, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_6, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_7, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_7, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_7, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_7, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_7, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_7, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_$HL$, 2, 16, { { REF_7, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "RES", INST_res_n_r, 2, 8, { { REF_7, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_0, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_0, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_0, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_0, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_0, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_0, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_0, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_0, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_1, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_1, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_1, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_1, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_1, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_1, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_1, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_1, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_2, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_2, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_2, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_2, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_2, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_2, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_2, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_2, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_3, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_3, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_3, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_3, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_3, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_3, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_3, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_3, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_4, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_4, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_4, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_4, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_4, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_4, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_4, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_4, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_5, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_5, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_5, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_5, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_5, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_5, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_5, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_5, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_6, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_6, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_6, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_6, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_6, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_6, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_6, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_6, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_7, false, true}, { REF_B, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_7, false, true}, { REF_C, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_7, false, true}, { REF_D, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_7, false, true}, { REF_E, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_7, false, true}, { REF_H, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_7, false, true}, { REF_L, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_$HL$, 2, 16, { { REF_7, false, true}, { REF_$HL, false, false}},false, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
        { "SET", INST_set_n_r, 2, 8, { { REF_7, false, true}, { REF_A, false, true}},true, { FLAG_NULL, FLAG_NULL, FLAG_NULL, FLAG_NULL} },
    };
}